In [51]:
#N维数组是机器学习和神经网络的主要数据结构
import torch


print("1、张量的创建")
#张量的一般创建
x = [7]
y = torch.tensor(x)# 通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值
print(y)

#几种特殊的数组创建方式
a = torch.zeros(3, 4)#创建一个3*4的张量，所有元素都是0
print(a)

b = torch.ones(3, 4)#创建一个3*4的张量，所有元素都是1
print(b)

c = torch.arange(1, 17)#创建一个一维张量，内容为[1,17)
print(c)

d = torch.randn(3, 4)#创建一个3*4的张量，每个元素都从均值为0、标准差为1的标准高斯（正态）分布中随机采样。
print(d)

#改变张量的形状
e = c.reshape(4, 4)
print(e)


print("2、张量的运算")
#张量的标准运算
m = torch.tensor([1, 2, 3, 4])
n = torch.tensor([5, 6, 7, 8])
print(m+n)
print(m-n)
print(m*n)
print(m/n)
print(m**n)#**运算符是求幂运算
print(torch.exp(m))#按元素作指数运算

#张量的连接
i = torch.arange(16).reshape(4, 4)
j = torch.arange(16, 32).reshape(4, 4)
print(i)
print(j)
print(torch.cat((i, j), dim=0))#dim=0为按行合并，即每一行上的元素是不变的
print(torch.cat((i, j), dim=1))#dim=1为按列合并，即每一列上的元素是不变的
#以此类推，三维张量可以用dim=2合并

'''
通过比较、逻辑运算符构建二元张量
比较运算符: ==  !=  >  <  >=  <=
逻辑运算符: and（与）  or（或）  not（非）
'''
print(i==j)

print(i.sum())#对张量中每一个元素求和


print("3、广播机制")
p = torch.arange(0,3).reshape(3,1)
q = torch.arange(0,4).reshape(1,4)
print(p)
print(q)
print(p+q)#在计算p+q时，p复制产生了一个3*4的张量，q复制产生了一个3*4的张量，然后按元素相加


print("4、元素的访问 索引与切片")
h = torch.arange(12).reshape(3,4)
print(h[0, 0])#访问第0行第0列
print(h[-1])#访问第-1行，即最后一行
print(h[0:2])#访问第0、1行
h[0, 0]=7#将元素写入矩阵
print(h)
h[0:2, 0:3]=17#将同一元素写入矩阵多个位置
print(h)


print("5、节约内存（针对占用内存较大的数据）")
t=torch.tensor([1, 2, 3, 4])
T=torch.tensor([5, 6, 7, 8])
id_t=id(t)
t=t+T
print(id_t==id(t))

#使用X[:]=X+Y或者X+=Y可以节约内存
t=torch.tensor([1, 2, 3, 4])
T=torch.tensor([5, 6, 7, 8])
id_t=id(t)
t[:]=t+T
print(id_t==id(t))

t=torch.tensor([1, 2, 3, 4])
T=torch.tensor([5, 6, 7, 8])
id_t=id(t)
t+=T
print(id_t==id(t))


print("6、转换成其他python类型")
X=torch.arange(16).reshape(4, 4)
import numpy# numpy是python中最基础的多元数组的运算框架
Y=X.numpy()#转换成numpy的多元数组
Z=torch.tensor(Y)#转换成张量
print(X, Y, Z)

#将大小为1的张量转换成python标量
a=torch.tensor([17.7])
print(a, a.item(), float(a), int(a))
print(type(a.item())==type(float(a)))


1、张量的创建
tensor([7])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])
tensor([[ 0.9985, -0.9339, -2.5359,  0.6142],
        [ 0.7892, -0.8687,  1.2635, -0.3803],
        [ 0.4767, -1.1482, -0.3057,  0.8225]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
2、张量的运算
tensor([ 6,  8, 10, 12])
tensor([-4, -4, -4, -4])
tensor([ 5, 12, 21, 32])
tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([    1,    64,  2187, 65536])
tensor([ 2.7183,  7.3891, 20.0855, 54.5981])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12

In [33]:
import torch
a = torch.tensor([1, 2, 3, 4])
print("id(a):",id(a))
b=torch.arange(4,8)
print("id(b):",id(b))

a=a+b
print(id(a))

id(a): 2589715273184
id(b): 2589715967648
2589468624352
